### ISSUE TITLE
Green Highlight & "One Page" for entire site

### ISSUE THREAD

**Issue by dev-bhatia** [dev-bhatia/dev-bhatia.github.io#6]
Green Underline should be active when user clicks on about/projects/blog/etc. And instead of linking to a different html page, site should render section (about/projects/etc) right there.

**Comment by r-jo** [comment]
The features are you asking for in this issue can be solving by using ReactJS and React-Router. I'm not sure how familiar you are with React but it's main feature is being able to render all the elements (including different pages) via javascript without reloading the entire page. Otherwise we will have to resort to using some hacky methods. I can take a look at some of my previous portfolio iterations and see if I can generate an easy to use boiler plate for you and let you see if you'd be interested in using React.

**Comment by dev-bhatia** [comment]
Not using component format/React for simplicity
